### ISSUE TITLE
Reverse proxy providing SSL in front of JIRA

### ISSUE THREAD

**Issue by charandas** [blacklabelops/jira#10]
I ended up needing a connector like this in `server.xml`. Otherwise, JIRA would keep reporting the scheme mismatch wherein the diagnostics detect `https` (due to accessing on secure URL) and JIRA would detect `http` given tomcat configuration within the container.

```xml
<Connector acceptCount="100"
              connectionTimeout="20000"
              disableUploadTimeout="true"
              enableLookups="false"
              maxHttpHeaderSize="8192"
              maxThreads="150"
              minSpareThreads="25"
              port="8080"
              protocol="HTTP/1.1"
              redirectPort="8443"
              useBodyEncodingForURI="true"
              scheme="https"
              proxyName="jira.example.com"
              proxyPort="443" />
```

And a Dockerfile like so:
```
FROM blacklabelops/jira:core.7.3.0
ADD server.xml /opt/jira/conf
```

Do you think this is a generic enough use-case that it can be supported through an ENV variable through `blacklabelops/jira`?

**Comment by charandas** [comment]
Followed this [doc](https://confluence.atlassian.com/adminjiraserver071/integrating-jira-with-apache-using-ssl-802593043.html).

**Comment by blacklabelops** [comment]
Still thinking about this. Can you please point out the exact difference/change/attribute you need to make it work?

Best solution will be an env, where you can set attributes. E.g. in db-config, config and Connector. A perfect feature for all of my Atlassian images. Can't name a delivery date though.

**Comment by blacklabelops** [comment]
Jira behind https proxy, these are the required environment variables:

JIRA_PROXY_NAME=yourproxyhost
JIRA_PROXY_PORT=443
JIRA_PROXY_SCHEME=https
