### ISSUE TITLE
OAuth configuration

### ISSUE THREAD

**Issue by BarnumD** [blacklabelops/jira#107]
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description
I'm considering enabling [oauth authentication ](https://developer.atlassian.com/server/jira/platform/oauth/)for an application.  The instructions reference using openssl.  My question is simply 1) If anyone else has enabled oauth.  2) Should this image contain tools listed in the help document, such as openssl.

### Versions
7.6.2

### Logs And Environment Information
```
openssl genrsa -out jira_oauth_privatekey.pem 1024
bash: openssl: command not found
```

**Comment by blacklabelops** [comment]
Can you explain on how to setup oauth? Is there the need that the Jira image itself must generate the certificate?

**Comment by BarnumD** [comment]
I still haven't fully got it configured with my application.  However, I did realize I could use openssl on any computer and copy the public/private keys to wherever I needed.  So I don't think it will be necessary in the package.
