### ISSUE TITLE
Update server.xml for compatibility with Tomcat 8.5.32+

### ISSUE THREAD

**Issue by jhult** [blacklabelops/jira#113]
As of 7.12.2+ the following needs to be added to the server.xml:
```
<Connector port="8080" relaxedPathChars="[]|" relaxedQueryChars="[]|{}^&#x5c;&#x60;&quot;&lt;&gt;" maxThreads="150" minSpareThreads="25" connectionTimeout="20000" enableLookups="false" maxHttpHeaderSize="8192" protocol="HTTP/1.1" useBodyEncodingForURI="true" redirectPort="8443" acceptCount="100" disableUploadTimeout="true" bindOnInit="false"/>
```

It looks like we might do that in [docker-entrypoint.sh](https://github.com/blacklabelops/jira/blob/master/imagescripts/docker-entrypoint.sh).

### More reading
- https://confluence.atlassian.com/jirasoftware/jira-software-7-12-x-upgrade-notes-955173978.html
- https://jira.atlassian.com/browse/JRASERVER-67974

**Comment by blacklabelops** [comment]
According to JRASERVER-67974 this will be fixed in the next version. As I read it, there is no need to add this in the fixed version.

**Comment by jhult** [comment]
From here: https://confluence.atlassian.com/jirakb/changing-server-xml-to-handle-requests-with-special-characters-958453799.html

> If you’re installing Jira from scratch, regardless of the version, you’re good to go, as the new server.xml file will contain the right properties.

> If you’re upgrading from Jira 7.12.1 or earlier to any later version, make sure you don’t just copy the old server.xml file into the new version, but add the required properties (as described below)

I think the way this is setup using Docker, we always use the latest server.xml from the instalalation and thus no changes would be necessary. @blacklabelops, can you confirm?

**Comment by blacklabelops** [comment]
Confirmed. The server.xml is inside the image and will be discarded with any container.

Entrypoint always updates the server.xml at every container start.
