### ISSUE TITLE
Feature request: Sync clock to NTP server

### ISSUE THREAD

**Issue by jhult** [blacklabelops/jira#118]
Sync clock inside Docker container to NTP server (of a user's choice).

We could possibly using [Chrony](https://chrony.tuxfamily.org).

**Comment by blacklabelops** [comment]
Time is the responsibility of the docker host. There is no sane way to set time inside the docker container.

See here: https://stackoverflow.com/questions/24551592/how-to-make-sure-dockers-time-syncs-with-that-of-the-host

No sane way, using a lib to intercept all system call and programs use to retrieve the current time and date: https://serverfault.com/questions/824631/how-to-set-system-time-dynamically-in-a-docker-container

**Comment by jhult** [comment]
Then this can be closed.
