### ISSUE TITLE
Restore backup using this image

### ISSUE THREAD

**Issue by doasare** [blacklabelops/jira#123]
I have a backup and want to import it using this image but get file not found. I checked the image in docker interactive console with user jira and the file exists. This is my extended docker image. Any help?
`
FROM blacklabelops/jira

USER root

RUN mkdir -p /var/atlassian/jira/
ADD 26_02_2019_Jira.zip /var/atlassian/jira/import/
RUN chown -R jira:jira /var/atlassian/jira
RUN chmod -R 755 /var/atlassian/jira

USER jira
CMD ["jira"]

`

**Comment by blacklabelops** [comment]
Won't work, because /var/atlassian is a volume.

You need to start the container and then use `docker cp ...` to copy your file to the volume.

Afterwards use `docker execute ...` to set permissions on file.

**Comment by doasare** [comment]
Thanks, i am actually very close.
any idea how to run the exec command

getting following error
The file at /var/atlassian/jira/import/26_02_2019_Jira.zip was not readable by the Jira process. Please check the file's permissions.

**Comment by blacklabelops** [comment]
Should be:

`docker exec -u root jira chmod 755 /var/atlassian/jira/import/26_02_2019_Jira.zip`

**Comment by doasare** [comment]
Thanks that work. 
I had to run these 2 commands first to get it to work
sudo docker exec -i -t  jira /bin/bash
chmod 777 .
