### ISSUE TITLE
Proposal: To have more than one db on the same container

### ISSUE THREAD

**Issue by evleite** [blacklabelops/jira#13]
It would be great to configure more than one db on the same container and it could be used on docker compose file like this:

docker run --name postgres -d \
    -e 'POSTGRES_USER=jira' \
    -e 'POSTGRES_PASSWORD=jellyfish' \
    -e 'POSTGRES_DB1=jiradb' \
    -e 'POSTGRES_ENCODING1=UNICODE' \
    -e 'POSTGRES_COLLATE1=C' \
    -e 'POSTGRES_COLLATE_TYPE1=C' \
    -e 'POSTGRES_DB2=confluencedb' \
    -e 'POSTGRES_ENCODING2=UNICODE' \
    -e 'POSTGRES_COLLATE2=C' \
    -e 'POSTGRES_COLLATE_TYPE2=C' \
    -e 'POSTGRES_DB3=bitbucketdb' \
    -e 'POSTGRES_ENCODING3=UNICODE' \
    -e 'POSTGRES_COLLATE3=C' \
    -e 'POSTGRES_COLLATE_TYPE3=C' \
    blacklabelops/postgres

This way we can have one single db server/container.

**Comment by blacklabelops** [comment]
Nice proposal. Please open a ticket on my repository blacklabelops/postgres!

**Comment by evleite** [comment]
ok. Thanks.
