### ISSUE TITLE
Update to Jira 7.3.3

### ISSUE THREAD

**Issue by dblM90** [blacklabelops/jira#14]
Hello,

first i want to thank you for sharing this useful, easy to use, docker container. It works very well on my server. The only thing is that i want to update to version 7.3.3. Will there be a newer image coming soon with this version?

Best regards,

Merlin

**Comment by blacklabelops** [comment]
Glad your asking!

**Comment by blacklabelops** [comment]
Should be available in at most twenty minutes.

**Comment by dblM90** [comment]
I ran into trouble pulling a newer image from docker hub. Is there the old version 7.3.1 yet?

**Comment by blacklabelops** [comment]
Build failed because there had been no Jira Servicedesk version 3.3.3. The next version is 3.4.0. This also affected the Jira Software build.

Yes, the old versions are always available. Just not build and updated daily.
