### ISSUE TITLE
Heads up!

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/jira#21]
Really nice work here, almost entirely complete, even a matching postgresql handling the encoding. 

I just wanted to thank you! I am creating a public rancher catalog on top of your images, thank you!

**Comment by EugenMayer** [comment]
And something else, thank you for not deleting the old tags..since thats what we also going to need, test older JIRA versions, which is just right possible OOTB.

**Comment by EugenMayer** [comment]
Thats how the rancher catalog looks like https://github.com/EugenMayer/docker-rancher-extra-catalogs/tree/master/templates/jira/0 - based on both, your jira and postgresql images. Thank you for your hard work!

I will for sure add confluence also.

**Comment by blacklabelops** [comment]
Thanks for using this image. I guess there is no real issue here so I just close this issue.
