### ISSUE TITLE
Explain volume usages

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/jira#23]
Its uncommon for images to not talk about data persistence. That said, since it can lead to serious issues that people use anon volumes ( docker-compose down and your killed ), you should update each example mounting a named volume at `/var/atlassian/jira` and `/var/lib/postgresql` - its regular practice to do so since it protects from a lot of harm.

I am aware, that people should actually know that, but that is a good reminder.

**Comment by blacklabelops** [comment]
There you go!

**Comment by EugenMayer** [comment]
perfect stuff, will help people not running into hell ( some of those ) :)
