### ISSUE TITLE
Explain the need of JIRA_DELAYED_START or better use wait-for-it

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/jira#25]
you need https://github.com/blacklabelops/jira/blob/master/docker-compose.yml#L20 to ensure DB is started before jira tries to access it but its not documented and will lead to random issues for people.

I would suggest you add it to the docs, or, i rather would suggest using wait-for-it https://github.com/vishnubob/wait-for-it

```
COPY ./bin/wait-for-it.sh /usr/local/bin/wait-for-it
```

on the top of the docker-entrypoint.sh

```bash
wait-for-it -t 60 -h db -p 5432
```

and thats it for the guard. Bootstrap starts when the DB is available

**Comment by blacklabelops** [comment]
That's a great idea, I am waiting for your pull request!

**Comment by EugenMayer** [comment]
@blacklabelops added the first part, the second part seems to get more complicated.

Eventhough i find it best-practise to always use "db" as an alias in the applicatians and let others either use links or external_links to deal with renames, i guess you have chosen a different path.

This makes it all a bit more complicated since JIRA_DATABASE_URL includes the database hostname - do you have a little parser for that already, splitting out the database URL so i can use it?

**Comment by blacklabelops** [comment]
Have you tested wait-for-it inside the container? Last time I remember I wasn't able to get it running under alpine.

**Comment by blacklabelops** [comment]
I already implemented a solution for this with `netcat`. Can't find it though. Need some sleep. Cya!

**Comment by EugenMayer** [comment]
Just tried it on a fresh alpine, i had to add bash but other then that it worked

```
 ./wait-for-it.sh -h 127.0.0.1 -p 38 -t 10
wait-for-it.sh: waiting 10 seconds for 127.0.0.1:38
```
adding bash to the container in the PR

**Comment by blacklabelops** [comment]
My solution can be found here, I am already using docker-wait inside my confluence image. 

https://github.com/blacklabelops/confluence/tree/development#database-wait-feature

**Comment by EugenMayer** [comment]
well if you want to use your other solution, why not. Pitty you did not remember this beforehand :)

**Comment by blacklabelops** [comment]
Realized using dockerize: https://github.com/jwilder/dockerize
