### ISSUE TITLE
Any plans to mount / modify cacerts

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/jira#26]
Due to the current nature of lets-encrypt certificates with java ( included starting from 1.8u57 or something)  creating applications links between jira/bamboo/confluence/bitbucketserver does not work unless the LE root / chain is imported into the java cacerts..

which is not located in the data folder, but rather in the codebase.

Do you plan to work on this kind of thing - any ideas how we could tackle this?

**Comment by xrobau** [comment]
https://github.com/blacklabelops/jira/blob/master/Dockerfile#L82

It's already there.

**Comment by EugenMayer** [comment]
impressive foresight! *bows*
