### ISSUE TITLE
Guide to create a bitbucket-server docker image

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/jira#30]
I understand that this issue is not jira related, but i am not sure how i would reach you witch such a topic best.

I would like to create a bitbucket server docker image, based on what you do. 

Are there any starting points you want to me to look at - i can try to get along with your Dockerfile here, i surely have to somehow adjust the answerfile and things like that.

Any chance you would like to join efforts and do this under your flag, blacklabelops/bitbucket?

There is also https://bitbucket.org/atlassian/docker-atlassian-bitbucket-server - so there is also a question if it makes sense - it seems to be maintained

**Comment by blacklabelops** [comment]
Your always invited to contribute to blacklabelops/bitbucket: https://github.com/blacklabelops/bitbucket

Please open any issues regaring bitbucket there, not here.

**Comment by EugenMayer** [comment]
i am must be freaking blind. i am really sorry. I _looked_ for it in your namespace but must missed it.

Joining you there, thanks and sorry
