### ISSUE TITLE
Add timezone handling for JIRA

### ISSUE THREAD

**Issue by EugenMayer** [blacklabelops/jira#31]
it can be critical to have a different timezone then UTC if you migrated your jira, e.g. for worklogs and tempo.

**Comment by EugenMayer** [comment]
https://wiki.alpinelinux.org/wiki/Setting_the_timezone

**Comment by EugenMayer** [comment]
so all we probably need is

```
apk add --update tzdata
cp /usr/share/zoneinfo/$TZ /usr/localtime
```

while we default $TZ to "UTC" so no current setups are harmed in any way.

**Comment by blacklabelops** [comment]
Do you have encountered any problem with using the environment variable TZ?

**Comment by EugenMayer** [comment]
which one?

**Comment by blacklabelops** [comment]
I am running several of my images simply with `TZ=Europe/Berlin`. All instances show the correct system time. What's the difference/advantage of the described approach?

**Comment by Firefishy** [comment]
Setting TZ= is also likely a performance win: https://blog.packagecloud.io/eng/2017/02/21/set-environment-variable-save-thousands-of-system-calls/

**Comment by blacklabelops** [comment]
I guess, this is settled then.
