### ISSUE TITLE
request: allow for reverse proxy as <domain/ip-address>/jira

### ISSUE THREAD

**Issue by wivaku** [blacklabelops/jira#32]
The following currently fails:

```
docker network create jiranet
docker run -d --name jira --network jiranet -v jiravolume:/var/atlassian/jira -e "JIRA_PROXY_NAME=10.0.0.21” -e "JIRA_PROXY_PORT=8111” -e "JIRA_PROXY_SCHEME=http” blacklabelops/jira
docker run -d -p 8111:80 --network jiranet --name nginx -e "SERVER1REVERSE_PROXY_LOCATION1=/jira” -e "SERVER1REVERSE_PROXY_PASS1=http://jira:8080” blacklabelops/nginx
```

Gives an error message when visiting http://10.0.0.21:8111/jira

> Oops, you've found a dead link

**Comment by blacklabelops** [comment]
The env variable is "JIRA_CONTEXT_PATH".

Example: `-e "JIRA_CONTEXT_PATH=/jira"`

**Comment by wivaku** [comment]
Thanks. To be sure, this is to be implemented in a future release?
When using it I get a 404 when going to http://10.0.0.21:8111/jira

```
docker network create jiranet

docker run -d --name jira --network jiranet -v jiravolume:/var/atlassian/jira -e "JIRA_PROXY_NAME=10.0.0.21" -e "JIRA_PROXY_PORT=8111" -e "JIRA_CONTEXT_PATH=/jira" -e "JIRA_PROXY_SCHEME=http" blacklabelops/jira

docker run -d -p 8111:80 --network jiranet --name nginx -e "SERVER1REVERSE_PROXY_LOCATION1=/jira" -e "SERVER1REVERSE_PROXY_PASS1=http://jira:8080" blacklabelops/nginx
```

**Comment by blacklabelops** [comment]
Build system is down, you will have to checkout the master and build it yourself.

**Comment by wivaku** [comment]
ok, thanks. Not sure how to build, so will wait until build system is up again. No worries.

**Comment by wivaku** [comment]
It appears the environment variable is set. But not as expected.

When using `-e "JIRA_CONTEXT_PATH=/jira123"`, I see in /opt/jira/conf/server.xml:
```
                <Context                                                 
            path="//jira123"
            docBase="${catalina.home}/atlassian-jira"                     
            reloadable="false"
            useHttpOnly="true"
          >                                                                  
```
Note the //jira123 instead of [/jira123](https://confluence.atlassian.com/jirakb/how-to-change-the-jira-application-context-path-225119408.html).

When using `-e "JIRA_CONTEXT_PATH=jira123"` (no leading slash), the server.xml looks ok and the initial request is made to https://mydomain.com/jira123 but then the subsequent requests for the page elements are made to https://jira123 , e.g. `https://jira123/s/-ovynku/73107/b6b48b282982abc129586ac216d119363/_/images/icon-jira-logo.png`

**Comment by blacklabelops** [comment]
New image is updated on dockerhub.

**Comment by ckotte** [comment]
I still have the issue with the two // in build 7.4.0. I need to use JIRA_CONTEXT_PATH: "jira" instead of JIRA_CONTEXT_PATH: "/jira"

**Comment by blacklabelops** [comment]
Thank you for taking a look into this issue. I will fix it.

**Comment by blacklabelops** [comment]
Can you please tell me which operating system your using? I don't have the issue with double "//"

My command:

~~~~
$ docker run -it -e "JIRA_CONTEXT_PATH=/jira" -e "DEBUG=true" blacklabelops/jira cat /opt/jira/conf/server.xml
~~~~

I get:

~~~~
path="/jira"
~~~~

**Comment by ckotte** [comment]
hm. I run docker compose on my Mac and the containers run on my QNAP NAS.

I just tested the above command directly on my NAS and I don't have two //...!?

**Comment by blacklabelops** [comment]
Yes, the parameters are already escaped, when it's passed inside Docker. Where do you enter your environment variables? Some QNAP frontend or docker-compose?

**Comment by ckotte** [comment]
it's via docker-compose from my Mac.

I think it's related to the launch.sh. It works when I remove the / from: CONTEXT_PATH="/$JIRA_CONTEXT_PATH"

**Comment by blacklabelops** [comment]
Yes, have not seen that one. That's exactly what's causing it, not an operating system issue.

**Comment by blacklabelops** [comment]
This fix introduces the env variable `JIRA_PROXY_PATH` without escaping and overwriting the legacy behavior of `JIRA_CONTEXT_PATH`. 

`JIRA_CONTEXT_PATH` will remain for downwards compatibility.

**Comment by ckotte** [comment]
Why do we need the old behavior for downwards compatibility?

Now we have:
CONFLUENCE_CONTEXT_PATH: "/confluence"
JIRA_PROXY_PATH: "/jira"
BITBUCKET_CONTEXT_PATH: "/bitbucket"

Isn't it possible to rename JIRA_PROXY_PATH to JIRA_CONTEXT_PATH and use JIRA_CONTEXT_PATH_OLD or something?? Then the envs for context paths would be similar in all products.

**Comment by blacklabelops** [comment]
Because I have >200k pulls on Dockerhub and this might break peoples running systems.
