### ISSUE TITLE
Can't connect to Atlassian Marketplace due to DNS issues

### ISSUE THREAD

**Issue by marton78** [blacklabelops/jira#34]
Sorry if this is a general Docker issue and not due to your images, but JIRA can't connect to Marketplace. I guess it's due to name resolution not working from inside the container:

```
# docker exec -it jira /bin/bash
bash-4.3$ nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'google.com': Try again
```

Any idea on how to fix this? I'm using your `docker-compose.yml`.

PS:

```
Docker version 17.05.0-ce, build 89658be
docker-compose version 1.13.0, build 1719ceb
```

**Comment by blacklabelops** [comment]
Please check this page: https://docs.docker.com/engine/userguide/networking/default_network/configure-dns/

**Comment by marton78** [comment]
Yes, I know this page, but it doesn't speak about `docker-compose`. I have changed your `docker-compose.yml` to include the setting `dns: 8.8.8.8` and verified that `docker inspect` shows this address as dns, but `nslookup` still fails. Maybe it's related to [this issue](https://forums.docker.com/t/resolved-service-name-resolution-broken-on-alpine-and-docker-1-11-1-cs1/19307/13), where users claim the problem is due to the line `options ndots:0` injected into `resolv.conf`. Indeed the container's `resolv.conf` looks like:

```
search mydomain.com
nameserver 127.0.0.11
options ndots:0
```

Does name resolution work for you with your provided `docker-compose.yml`?

**Comment by blacklabelops** [comment]
I verified:

~~~~
$ curl -O https://raw.githubusercontent.com/blacklabelops/jira/master/docker-compose.yml
$ docker-compose up -d
$ docker-compose exec jira
$ nslookup google.com

Name:      google.com
Address 1: 216.58.207.174 muc11s04-in-f14.1e100.net
Address 2: 2a00:1450:4016:807::200e muc11s04-in-x0e.1e100.net
~~~~

Your docker-demon is not able to configure the network bridge correctly. You container's are not able to connect to the internet. Can't help you with more.

**Comment by marton78** [comment]
Thanks, @blacklabelops. The issue was entirely unrelated to Docker: our internal DNS server didn't accept recursion from Docker's subnet. I needed to add

```
allow-recursion { 127.0.0.1; 10.0.0.0/8; 172.16.0.0/12; };
```

to `bind.conf`. Confusion arose from the line `nslookup: can't resolve '(null)': Name does not resolve` which is apparently unique to `alpine`, other containers don't show it. Now the line still appears, but name resolution works:

```
# docker exec -it jira nslookup google.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      google.com
Address 1: 172.217.17.142 ams15s30-in-f14.1e100.net
Address 2: 2a00:1450:400e:807::200e ams15s30-in-x0e.1e100.net
```

Thanks, closing.
