### ISSUE TITLE
Add SQLServer support to common.sh

### ISSUE THREAD

**Issue by joshbtn** [blacklabelops/jira#40]
It would be nice if this would also support SQLserver.  I've tested this by adding the following: 

imagescripts\common.sh
```bash
    *:sqlserver)
      if [ -z "$(read_var $prefix PORT)" ]; then
        eval "${prefix}_PORT=1433"
      fi
      local host_port_name="$(read_var $prefix HOST):$(read_var $prefix PORT)/$(read_var $prefix NAME)"
      local jdbc_driver="net.sourceforge.jtds.jdbc.Driver"
      local jdbc_url="jdbc:jtds:sqlserver://$host_port_name"
      local hibernate_dialect="org.hibernate.dialect.SQLServerDialect"
      local database_type="mssql"
      ;;
```
imagescripts\launch.sh
```bash
if [ "$JIRA_DB_TYPE" == "mssql" ]; then
    SCHEMA='<schema-name>dbo</schema-name>'
fi
```

**Comment by blacklabelops** [comment]
This would need a driver, please take a look inside the Dockerfile how drivers are added.

**Comment by joshbtn** [comment]
It actually already ships with the jtds driver. It's located at /opt/jira/lib/jtds-1.3.1.jar.  I followed these instructions https://confluence.atlassian.com/adminjiraserver071/connecting-jira-applications-to-sql-server-2012-802592195.html

**Comment by blacklabelops** [comment]
Implemeted, pls check.

**Comment by joshbtn** [comment]
Sorry for the delay!  I verified this is working for me. Thanks!
