### ISSUE TITLE
7.5.0 release

### ISSUE THREAD

**Issue by ain** [blacklabelops/jira#46]
Would be nice if there was `7.5.0` release as well. Thanks in advance!

**Comment by blacklabelops** [comment]
Build failed, I'm taking a look.

**Comment by blacklabelops** [comment]
Simple rebuild fixed the issue.

**Comment by ain** [comment]
Brilliant! Thanks so much @blacklabelops. By the way, why don't you add https://hub.docker.com/r/blacklabelops/jira/ as a homepage link of this Github repo. Would make navigation simpler from here :)
