### ISSUE TITLE
docker-compose up 

### ISSUE THREAD

**Issue by yudong2015** [blacklabelops/jira#5]
使用docker-compose up -d启动jira的时候报下面的错误：
__jirasoftware  | mkdir: can't create directory '/var/atlassian/jira/log': Permission denied__

![1 pic_hd](https://cloud.githubusercontent.com/assets/14155338/16994244/22ea8058-4ed9-11e6-8799-6e8d36839b47.jpg)

**Comment by blacklabelops** [comment]
This usually happens when you volume folders from windows.

Which operating system do you use?

Do you use  volumes? Which folders?

You can try to start container under user root!

**Comment by yudong2015** [comment]
The OS is ubuntu14.  I have used volumes . My docker-compose is:
version: '2'

services:
  jira:
    image: blacklabelops/jira
    container_name: jirasoftware
    networks:
    ┊ - jiranet
    volumes:
    ┊ - /data/volumes/jira/jiradata:/var/atlassian/jira
    ports:
    ┊ - '8092:8080'
    environment:
    ┊ - 'JIRA_DATABASE_URL=postgresql://jira@postgresql/jiradb'
    ┊ - 'JIRA_DB_PASSWORD=jellyfish'
    ┊ - 'CATALINA_OPTS= -Xms256m -Xmx1g'
    ┊ - 'JIRA_PROXY_NAME='
    ┊ - 'JIRA_PROXY_PORT='
    ┊ - 'JIRA_PROXY_SCHEME='
    ┊ - 'JIRA_DELAYED_START=10'
    links:
    ┊ - 'postgresql:postgresql'
    labels:
    ┊ com.blacklabelops.description: "Atlassian Jira"
    ┊ com.blacklabelops.service: "jira"

  postgresql:
    image: blacklabelops/postgres
    hostname: postgresql
    networks:
    ┊ - jiranet
    volumes:
    ┊ - /data/volumes/jira/postgresql:/var/lib/postgresql/data
    environment:
    ┊ - 'POSTGRES_USER=jira'
    ┊ # CHANGE THE PASSWORD!
    ┊ - 'POSTGRES_PASSWORD=jellyfish'
    ┊ - 'POSTGRES_DB=jiradb'
    ┊ - 'POSTGRES_ENCODING=UNICODE'
    ┊ - 'POSTGRES_COLLATE=C'
    ┊ - 'POSTGRES_COLLATE_TYPE=C'
    labels:
    ┊ com.blacklabelops.description: "PostgreSQL Database Server"
    ┊ com.blacklabelops.service: "postgresql"

#volumes:
#  jiradata:
#    external: false
#  postgresqldata:
#    external: false
# 

networks:
  jiranet:
    driver: bridge


And I also try it under user root , bun it does not work.  I think that is error in container , the user in container is not root.

**Comment by blacklabelops** [comment]
The problem: User inside container (jira:jira userid=1000, groupid=1000) has no access to your local Ubuntu folder /data/volumes/jira/jiradata.

There are several solutions, the easiest is to run the container with user root:

~~~~
services:
  jira:
    image: blacklabelops/jira
    container_name: jirasoftware
    user: root
~~~~

**Comment by yudong2015** [comment]
It does not work
![1 pic_hd](https://cloud.githubusercontent.com/assets/14155338/17019554/6e3089ea-4f6f-11e6-9f95-1fd2b2d135ca.jpg)


Other solutions?
Do you have try it on ubuntu?

**Comment by blacklabelops** [comment]
- Add some random user with user_id 1000 and group_id 1000 to your ubuntu system. Give user own rights to folder /data/volumes/jira/jiradata.

**Comment by blacklabelops** [comment]
I am not sure if docker volumes solves this issue:

Add this to you docker-compose file:

~~~~
volumes:
  jiradata:
    external: false
~~~~

Then configure your container to use the volume rather the folder:

~~~~
services:
  jira:
    image: blacklabelops/jira
    container_name: jirasoftware
    volumes:
      - jiradata:/var/atlassian/jira
~~~~

You can see where the volume is saved on your hard disk:

~~~~
$ docker volume inspect jiradata
~~~~

**Comment by blacklabelops** [comment]
Third solution:

Check out this project then adjust 

~~~~
export CONTAINER_UID=1000                       &&  \
~~~~

and 

~~~~~
export CONTAINER_GID=1000                       &&  \
~~~~~

To some user_id and group_id of your ubuntu system.

Build container like this:

~~~~
$ docker build -t blacklabelops/jira .
~~~~

Give user own rights to folder /data/volumes/jira/jiradata.

**Comment by blacklabelops** [comment]
Closing.

**Comment by rwarren** [comment]
For anyone else landing here and still needing help, docker volumes (mentioned above) DO solve the issue.

Automatically created volumes in the docker-compose file (or created externally with `docker volume create jiradata` and referenced in the compose file with `external: true`) issue get created with permissions that can be accessed from the container.
