### ISSUE TITLE
Crowd SSO Support Enabler/Disabler

### ISSUE THREAD

**Issue by blacklabelops** [blacklabelops/jira#55]
Request by someone to enable crowd SSO support.

Described here [Integrating Crowd with Atlassian JIRA](https://confluence.atlassian.com/crowd/integrating-crowd-with-atlassian-jira-192625.html)

Todo:

Environment variable to enable the following entry:

file:  `JIRA/atlassian-jira/WEB-INF/classes/seraph-config.xml`
Comment-Out: `<!--<authenticator class="com.atlassian.jira.security.login.JiraSeraphAuthenticator"/>-->`
Un-Comment: `<authenticator class="com.atlassian.jira.security.login.SSOSeraphAuthenticator"/> `

And vice versa.

**Comment by Firefishy** [comment]
Very similar for most of the products.

Bitbucket: bitbucket.properties add plugin.auth-crowd.sso.enabled=true
Confluence: seraph-config.xml uncomment.
JIRA / ServiceDesk: seraph-config.xml uncomment.

**Comment by blacklabelops** [comment]
We should make a ticket in each repository separately in order to be able to track its readiness.

**Comment by blacklabelops** [comment]
Implemented, released and ready to be tested!
