### ISSUE TITLE
always get postgresql timeout

### ISSUE THREAD

**Issue by Hendrik44** [blacklabelops/jira#59]
Running the docker-compose on ubuntu 16.04 will always run into the following error "Timeout after 1m0s waiting on dependencies to become available: [tcp://postgresql:5432]"

Running the same on mac osx all is fine. Is there any solution to fix it?

**Comment by blacklabelops** [comment]
Remove the environment variables `DOCKER_WAIT_HOST` and `DOCKER_WAIT_PORT`.

**Comment by Hendrik44** [comment]
I have already tested it without these environment variables. Without, anything crashed and jira isn't reachable via web browser.

**Comment by blacklabelops** [comment]
I have upgrade the docker-compose file. Maybe this works better for you.

**Comment by blacklabelops** [comment]
No feedback after weeks.

**Comment by Hendrik44** [comment]
Sry for late response, I’m currently very busy and and can’t test it on the same server. I will try it tomorrow on a different server with same setup and give you feedback,

**Comment by Hendrik44** [comment]
I've testet it and now it works fine. Thanks

**Comment by blacklabelops** [comment]
Thanks for the feedback!
