### ISSUE TITLE
Support for Postgres 10

### ISSUE THREAD

**Issue by asthomasdk** [blacklabelops/jira#63]
Will you be adding support for Postgres 10 with your Jira image? 

Although this is not officially supported yet, We have done this by including the latest postgres drivers in our internal builds. 

https://jdbc.postgresql.org/

**Comment by blacklabelops** [comment]
Is Postgres 10 officially supported by Jira? Last time i took a look it was not.

**Comment by Firefishy** [comment]
JIRA  7.7 only supports upto postgres 9.6: https://confluence.atlassian.com/adminjiraserver/supported-platforms-938846830.html

For general public it is likely best to stick to the bundled JDBC postgres driver, see the notes on the above link.

Personally I'd say build a custom image with an unsupported updated JDBC driver if you require it.

**Comment by blacklabelops** [comment]
Even if it's supported we need it configurable. We would still need the postgres 9.x drivers and I do not think it's healthy to put both in the classpath.

**Comment by blacklabelops** [comment]
If I understand correctly it would be nice to have an option to switch between Jira packaged postgres drivers and the latest postgres drivers. The postgres drivers both support 9.x and 10.x in the latest versions but the packaged postgres drivers only supports 9.x.

Is this correct?

**Comment by Firefishy** [comment]
JIRA currently ships with postgres JDBC driver 9.4.1212 which looks like it should be compatible with PG10.

**Comment by blacklabelops** [comment]
Yes, I agree. Apparently, there is nothing like specific postgres 10 support inside postgres drivers. The packaged JDBC driver 9.4.1212 has at least JDBC 4.0 support to any postgres version.

As a result, you should be able to be able to take the image as it is :)

**Comment by asthomasdk** [comment]
Thanks for the input guys! 

I can confirm that we are able to use the image as it is with a pg 10 database. We have been testing that on a stack where we use pg for other things in addition to Jira. This seems to work ok. 

You get a warning in the Jira logs - but so far we have not seen any show stopping issues. 

I guess as long as Jira does not officially support pg 10, then we just stick with what we have now. I can live with that.
