### ISSUE TITLE
Add ability to configure proxy settings in server.xml

### ISSUE THREAD

**Issue by tboloo** [blacklabelops/jira#65]
When running jira behind the proxy some things like attachments does not work correctly, unless one logs into running jira container and update server config, adding proxy-related settings to the `<Connector/>` section, like so:

 ```
<Service  name="Catalina">
        <Connector
        port="8080"
        proxyName="external.proxy.address"
        proxyPort="443"
        scheme="https"
        secure="true"
        maxThreads="150"
        minSpareThreads="25"
        connectionTimeout="20000"
        enableLookups="false"
        maxHttpHeaderSize="8192"
        protocol="HTTP/1.1"
        useBodyEncodingForURI="true"
        redirectPort="8443"
        acceptCount="100"
        disableUploadTimeout="true"
        bindOnInit="false"
    />

```
It would be great if these settings could be passed as environment variables to the container.

**Comment by blacklabelops** [comment]
Which properties do you need? Because proxyName, proxyPort and scheme can be already set with `JIRA_PROXY_NAME`, `JIRA_PROXY_PORT` and `JIRA_PROXY_SCHEME`.

In the current version you can also use your custom server.xml. See here: https://github.com/blacklabelops/jira#custom-configuration

**Comment by tboloo** [comment]
You right, I have missed so obvious thing... Thanks for the prompt response, and keep up the good work.
