### ISSUE TITLE
Adding any certificate to the Java Keystore

### ISSUE THREAD

**Issue by esciara** [blacklabelops/jira#68]
Hi,

We need to add a certificate to the java keystore to allow Jira (and confluence) to connect to our internal user directory. This is already done for the letsencrypt certificates. 

Would it be possible to add variables to allow to do that for certificates of our choice ?

Em

**Comment by blacklabelops** [comment]
Best way to do this would be to extend the image. Write your extension Dockerfile and just add them simply to the store as I am doing with the letsencryp certificates.

**Comment by blacklabelops** [comment]
You can see the instructions here:

https://github.com/blacklabelops/jira#extending-this-image

**Comment by alktlr** [comment]
If you do not want to extend the image, you can inject cacerts into the container. What I have done is copy /opt/jira/jre/lib/security/cacerts to the host. Add the certificate to cacerts and mount it to the same path.

docker cp <container name>:/opt/jira/jre/lib/security/cacerts cacerts
keytool ...
docker run -v $(pwd)/cacerts:/opt/jira/jre/lib/security/cacerts ...

Remember to do the above again when java is upgraded together with the jira container.

**Comment by esciara** [comment]
Thanks for the tip. @alktlr 

> Remember to do the above again when java is upgraded together with the jira container.
I am trying to avoid to have to remember and looking for a programatic way to assure that it is done at each deployement, automatically.

Do you know of another way than extendi the container image, but that is programatic?

**Comment by blacklabelops** [comment]
Something like this? https://github.com/blacklabelops/bitbucket#ssh-keys

Can be done, though takes a while.

**Comment by alktlr** [comment]
You could script the extract of cacerts, keytool import and docker run. So these commands will be run on every startup.

**Comment by blacklabelops** [comment]
I think there are two issues involved.

1. How do you get your certificates into your environment
1. How do you get Jira to add your certificates.

There are two ways to get your certificates inside the environment.

1. Copy them into your environment (This includes to curl them from an url or retrieve them from some kind of storage).
1. Put them inside an image.

In my case, I usually tend to put certificates inside volume-images and build them each time I deploy containers.

Example with docker-compose:

~~~~
services:
  # Key container
  server_keys:
    build: ./keys
    container_name: keys
    volumes:
      - keys:/server_keys
    command: bash
~~~~

**Comment by esciara** [comment]
I know one of my colleagues worked on this... I will ask him what he went for in the end and let you know.
