### ISSUE TITLE
Add restart to docker-compose?

### ISSUE THREAD

**Issue by jhult** [blacklabelops/jira#71]
Would it be beneficial to add [restart: always](https://docs.docker.com/compose/compose-file/#restart) to [docker-compose.yml](https://github.com/blacklabelops/jira/blob/master/docker-compose.yml)?

**Comment by blacklabelops** [comment]
You should use: restart: unless-stopped

**Comment by Firefishy** [comment]
docker swarm doesn't use restart ;-)

**Comment by blacklabelops** [comment]
What does docker-swarm use?

**Comment by Firefishy** [comment]
Docker swarm has an implicit restart always. It doesn't support restart from docker-compose.yml

**Comment by blacklabelops** [comment]
How can you reconfigure restart in docker-swarm?
