### ISSUE TITLE
urldecode replaces % to x 

### ISSUE THREAD

**Issue by ageekymonk** [blacklabelops/jira#89]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description
If the username has %40 instead of replacing %40 to @, urldecode changes it to x40. This causes problem with database connection

### Steps to Reproduce

If username as hello@world, then when we pass in uri it will be postgres://hello%40world@db.com

**Expected behavior:** [What you expect to happen]
Username should be hello@world in the dbconfig.xml

**Actual behavior:** [What actually happens]

username ios hellox40world in the dbconfig.xml

**Reproduces how often:** 
100%

Have the fix. Will raise a pr as soon as i test it.

**Comment by jhult** [comment]
@blacklabelops, can this be closed now that it is merged?

**Comment by blacklabelops** [comment]
I waited for the response, but well.
