### ISSUE TITLE
JIRA core tag version 7.3.0 does not exist

### ISSUE THREAD

**Issue by charandas** [blacklabelops/jira#9]
The readme cites `core.7.3.0` as the latest tag available for JIRA core, but it does not exist on docker hub? Am I reading this correctly?

Thanks for awesome alpine images.

**Comment by blacklabelops** [comment]
Yes, accepted a "faulty" pull request. This project currently uses 3 Dockerfiles for each Jira version separately. Also, I have to update the build system for updating Dockerhub.

Should be solved now.

**Comment by charandas** [comment]
:+1:
