### ISSUE TITLE
docker-complose file is not working

### ISSUE THREAD

**Issue by scm20008** [blacklabelops/jira#93]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem.
    * Checked that your issue isn't already filed.
    * Filled the form.
    * Included logs and system information.

### Description

when boot jira app by using docker-compose, jira boot failed, cannot connect to mysql database.

if only using "docker run" commands to boot jira app, it is fine.

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

**Comment by blacklabelops** [comment]
Docker Compose file is for postgres database.

**Comment by scm20008** [comment]
thanks, I know that.

I modified my docker compose file according to yours before, maybe the file had some problem.
Finally, I figure it out, then I have no problem.
