### ISSUE TITLE
Should we move from MySQL driver 5.1.46 to 8.0.11?

### ISSUE THREAD

**Issue by jhult** [blacklabelops/jira#96]
Should we move [mysql-connector-java](https://dev.mysql.com/downloads/connector/j/) from 5.1.46 to [8.0.11](https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.11.tar.gz)?

Per their website:

> MySQL Connector/J 8.0 is highly recommended for use with MySQL Server 8.0, 5.7, 5.6, and 5.5. Please upgrade to MySQL Connector/J 8.0.

The only concern I would have is if they built for a higher Java version than the lowest version Atlassian supports for Jira.

**Comment by Firefishy** [comment]
It depends on what version of mysql-connector-java Atlassian recommend.

**Comment by Firefishy** [comment]
[This page](https://confluence.atlassian.com/adminjiraserver/connecting-jira-applications-to-mysql-938846854.html) says "f you are installing Jira, download the recommended MySQL driver JDBC Connector/J 5.1. "

**Comment by blacklabelops** [comment]
Let's keep the current driver until something breaks or there is a new recommendation.

**Comment by blacklabelops** [comment]
Final thought: 
When the database technology group recommends for a new driver version then it's a suggestion from technology group to application developer to use the latest database driver.

It's the task of the application developer, e.g. Atlassian Jira, to use and test the drivers and recommend and/or package the database drivers.

It's not the task of the application user or administrator to jump to versions and let's be truthful here, rather clueless.

I would rather keep to recommendations here. Always open to discuss.
