### ISSUE TITLE
CATALINA_OPTS/JVM_*_MEMORY variables don't work

### ISSUE THREAD

**Issue by Sebor** [blacklabelops/jira#98]
### Description

CATALINA_OPTS/JVM_*_MEMORY variables don't work

### Steps to Reproduce

1. Run container with -e "JVM_MINIMUM_MEMORY=1024m" or with -e "CATALINA_OPTS= -Xms256m -Xmx1g"
2. Check process: ps -ef | grep java
3. There are default values in output: -Xms384m -Xmx768m

**Expected behavior:** Java heapsize changes

**Actual behavior:** java heapsize doesn't change

**Reproduces how often:** always

### Versions
latest
### Logs And Environment Information
In catalina.log I see default values too.

**Comment by blacklabelops** [comment]
Confirmed.

* `JVM_MINIMUM_MEMORY` and `JVM_MAXIMUM_MEMORY` have no effect at all.
* CATALINA_OPTS will be just "attached" to the execution command and are therefore ineffective.

New proposed solution by Atlassian: https://confluence.atlassian.com/adminjiraserver073/increasing-jira-application-memory-861253796.html

Solution:

* Image must implement env variables `JVM_MINIMUM_MEMORY` and `JVM_MAXIMUM_MEMORY` and adjust property inside `setenv.sh`.

**Comment by blacklabelops** [comment]
Workaround: Do it manually. Has to be done each time container is replaced.

**Comment by blacklabelops** [comment]
Memory can be set now in accordance with Atlassian documentation, see here:

https://github.com/blacklabelops/jira#a-word-about-memory-usage

**Comment by Sebor** [comment]
Yes, it works. Thanks!
I guess the issue can be closed.
